# Generated by Django 3.2.12 on 2022-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transrss_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='id',
        ),
        migrations.AlterField(
            model_name='torrent',
            name='guid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
