# Generated by Django 3.2.12 on 2022-07-04 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transrss_manager', '0002_auto_20220704_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transrss_manager.feedsource'),
        ),
    ]
