# Generated by Django 3.2.12 on 2022-07-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transrss_manager', '0003_torrent_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedmatcher',
            old_name='matcher',
            new_name='pattern',
        ),
    ]
