# Generated by Django 3.2.16 on 2023-05-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transrss_manager', '0005_torrent_alive'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshing', models.BooleanField(default=False)),
            ],
        ),
    ]
